# Generated by Django 4.2 on 2023-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='file_submission',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='image_submission',
            field=models.ImageField(blank=True, null=True, upload_to='submission_images/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='link_submission',
            field=models.URLField(blank=True, null=True),
        ),
    ]
